version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: php-api-server
    image: laughface809/php_manifest:latest
    ports:
      - "1337:80"
    volumes:
      - .:/var/www
